import type { Metadata } from 'next'
import './globals.css'
import ThemeLayout from '../layout/ThemeLayout'
import Header from '../components/Header'
import Footer from '../components/Footer'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeLayout>
          <div className="max-w-7xl mx-auto px-10 max-lg:px-5 max-sm:px-[10px] flex flex-col min-h-screen h-full">
            <Header/>
            <div>
              {children}
            </div>
            <Footer/>
          </div>
        </ThemeLayout>
      </body>
    </html>
  )
}
